services:
  backend:
    build: .
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_YDy9TPVhB1gU@ep-long-moon-ad8lxqqc.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
